version: '3.9'

services:
  dbsrv:
    image: postgres:17
    container_name: ctnr-pgdb
    ports:
      - "5432:5432"
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_transferegov"]
      interval: 5s
      timeout: 5s
      retries: 5

  api_transferegov:
    container_name: ctnr-api_transferegov
    command: uvicorn --host 0.0.0.0 --port 8000 src.main:app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      dbsrv:
        condition: service_healthy            
    env_file:
      - .env

volumes:
  pgdata: